title: Block Breaker
description: >-
  This Game i am Making in Unity Engine in this game i will Make a Game like
  Jardinas 2 ,  this game will be a Single Player Game And Want to keep this
  project in Github Because in  Future if i want to make it multiplayer of it.
steps:
  - course: githubtraining/introduction-to-github
    description: The first step in your course
  - link: 'https://lab.github.com'
    title: Check out Learning Lab for more courses!
    description: >-
      There are many more courses available on Learning Lab for you to check
      out.
